name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version here

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt
      shell: bash

    - name: Run option pricing script
      run: |
        source venv/bin/activate
        python src/option_pricing.py
      shell: bash

    - name: Run backtesting script
      run: |
        source venv/bin/activate
        python src/backtesting.py
      shell: bash